### ISSUE TITLE
Add stats to export

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#19]
Add basic stats in the zip (number of files, breakdown by journal, etc.)

**Comment by madewild** [comment]
Dynamic stats based on actual content of export

**Comment by madewild** [comment]
@flecam @bdeseure vous voyez d'autres stats à ajouter dans le README du ZIP à par le nombre de fichiers par journal ?

**Comment by flecam** [comment]
@madewild @bdeseure Ce serait déjà bien. Sauf, si on peut aussi mettre des stats par année? héhéhé

**Comment by madewild** [comment]
OK pour journaux + années

**Comment by madewild** [comment]
@flecam @bdeseure c'est implémenté
Pouvez-vous tester sur https://dev.camille-ulb-kbr.be/?query=chicon&zip=true et me dire si je dois ajuster ?
