### ISSUE TITLE
Enrich "External Resources" page

### ISSUE THREAD

**Issue by anjacque** [madewild/CAMille#22]
CAMille will provide users with a set of external online resources related to the history of journalism in Belgium.

For the moment, only write "Under construction"

**Comment by madewild** [comment]
Enrich later

**Comment by madewild** [comment]
@anjacque will you provide this or should I postpone to v4 while waiting for someone else to assign it to?

**Comment by anjacque** [comment]
Florence said she would write this page. I have just asked her again if it is possible for this version. I will let you know as soon as possible.

**Comment by flecam** [comment]
La plateforme comprendra seulement des corpus. Les autres liens extérieurs vont être rapatriés sur la page CAMIlle de la KBR. @bdeseure tu confirmes?

**Comment by madewild** [comment]
Si c'est le cas on peut supprimer la page https://www.camille-ulb-kbr.be/?page=resources (et l'onglet de menu correspondant) qui est "En construction..." depuis le début.

**Comment by flecam** [comment]
Oui. On oublie.

**Comment by madewild** [comment]
Voilà c'est supprimé.
