### ISSUE TITLE
Add logos on about page

### ISSUE THREAD

**Issue by madewild** [madewild/camille#27]
@anjacque can you provide them?

**Comment by anjacque** [comment]
![logo-kbr](https://user-images.githubusercontent.com/65342272/117455900-ebe31a00-af47-11eb-9f0b-9f317194be8f.png)
![logo ulb bleu](https://user-images.githubusercontent.com/65342272/117455901-ec7bb080-af47-11eb-8327-89e3cb29fac7.jpg)
