### ISSUE TITLE
Rename README.txt into _README.txt

### ISSUE THREAD

**Issue by anjacque** [madewild/camille#29]
So that it will be by default the first file in the list, which is potentially 500 files long

**Comment by madewild** [comment]
Done but does not work for all platforms, as can be seen for me:
![zip](https://user-images.githubusercontent.com/942488/117455594-a45c8e00-af47-11eb-888b-7f72ead69228.png)

**Comment by madewild** [comment]
@anjacque what do you suggest? we can try with a 0 (zero) instead?

**Comment by anjacque** [comment]
I have the same as you in the zip file with "_README.txt", but it works when the zip is extracted.

**Comment by madewild** [comment]
Not on Linux with Gnome/Nautilus:
![nautilus](https://user-images.githubusercontent.com/942488/117458848-04086880-af4b-11eb-8065-28e9684c9541.png)
