### ISSUE TITLE
Filter by page number

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#32]
Parse id and reindex ES

**Comment by madewild** [comment]
@anjacque for this I put a quick filters like the others to test, but the list is a bit long and there are probably some bigger than 32...
should we go for a slider like the one of the years? it would allow single pages ("une") or ranges ("pages from 10 to 15") but not "first and last page" for instance.

**Comment by madewild** [comment]
Slider implementer in dev.
L'Indépendance belge of 04/06/1927 (special English edition) has 70 pages, so I put this as max value.
@anjacque can you test also this one? especially the interaction with other filters...

**Comment by anjacque** [comment]
It works but there are two problems with the text line containing the page numbers
1) It is too short on my screen: the end of the line is hidden even if there is still space on the right to make it appear (see picture)
![image](https://user-images.githubusercontent.com/65342272/132713731-6814ada7-af51-4edf-a4ea-ae46dab384d5.png)

2) The font is not the same as on the rest of the page (same problem as #47 )

**Comment by madewild** [comment]
The font should be fixed but I am unable to reproduce the other problem, I will need your help to debug it.

As for the move to another kind of filter, let's tackle this when the need arises. ;)

**Comment by madewild** [comment]
Created issue #48 for this.

**Comment by madewild** [comment]
Probably a css glitch, closing now but feel free to reopen if it arises again.
