### ISSUE TITLE
Filter by multiple months

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#33]
Parse id and reindex ES

**Comment by madewild** [comment]
Deployed in dev

**Comment by madewild** [comment]
@anjacque can you test?

**Comment by anjacque** [comment]
It works, thanks! Two questions:
1) Would it be possible to select multiple months (November AND December, for instance)?
2) Would it be possible (maybe when the "exact date filter" is developed) to request a specific period, like "from March 1902 to May 1903", or even "from 5 March 1902 to 6 May 1903"?
One thing to be discussed/fixed:
When you select a Month with this filter and change the period with the "Year filter" afterwards, the "Month filter" is automatically lost.

**Comment by madewild** [comment]
@anjacque Great testing, thanks. :) My answers:
1. it's the same as for journals, so I could implement the same solution
2. this is exactly the goal of the exact date filter ;)
3. this is a bug, will fix

**Comment by madewild** [comment]
@anjacque for 3 should be better now

I leave open for the multiple months

**Comment by madewild** [comment]
implemented in dev
