### ISSUE TITLE
Filter by day number

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#34]
Parse id and reindex ES

**Comment by madewild** [comment]
e.g. for 1st of May across years etc.

**Comment by madewild** [comment]
@anjacque same thing here, I created a first draft filter but maybe not convenient to have the 31 days listed and a range slider would be more appropriate?
ok stopping for tonight anyway :)

**Comment by madewild** [comment]
Slider implemented in dev.
@anjacque can you test?

**Comment by anjacque** [comment]
It works! Two things: 
1) The text line does not have the same font as the rest of the page (also see other issues).
2) We will have problems with that filter when we add other collections that are not newspapers (I think of the Annuaires de la presse belge, for instance, which can be more than 500 pages long, and that we are going to digitise soon). Wouldn't it be better to set two boxes with From [...] To [...], with the years to be manually typed by the user?

**Comment by anjacque** [comment]
It works, but the text line does not have the same font as the rest of the page (also see other issues).

**Comment by madewild** [comment]
Should be fine now, closing (if not you can reopen).
