### ISSUE TITLE
Filter by multiple days of the week

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#35]
Use universal calendar??

**Comment by madewild** [comment]
this is implemented in dev, @anjacque can you test?
also, do you also need multiple days selection like for journal and month?

**Comment by anjacque** [comment]
Thanks!
Yes, for the multiple days selection (it could be interesting to allow a request on "Saturdays AND Sundays" if someone is interested in weekends editions, for exemple).
I suppose that you know this, but we have the same bug here as in the "Month filter": changing the "Year filter" removes the "day of the week filter".

**Comment by madewild** [comment]
@anjacque oh I had misunderstood the issue! should be fixed now :)
I leave open for multiple days like saturday + sunday

**Comment by madewild** [comment]
implemented in dev
