### ISSUE TITLE
Top bar with filter summaries

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#38]
Like newseye, needed?

**Comment by madewild** [comment]
@anjacque open question for later...

**Comment by madewild** [comment]
Compare with https://platform.newseye.eu/en/catalog?f%5Blanguage_ssi%5D%5B%5D=fr&f%5Bmember_of_collection_ids_ssim%5D%5B%5D=la_presse&q=chicon&search_field=articles_exact_search

![topbar](https://user-images.githubusercontent.com/942488/191370580-a121e3ed-a2f6-4f0b-b073-aa56b1058b64.png)

**Comment by flecam** [comment]
Ce serait super!

**Comment by madewild** [comment]
D'accord mais je propose de postposer à début 2023 car il va falloir pas mal tester pour voir comment afficher ça quand plusieurs journaux sont sélectionnés en même temps, etc.

**Comment by flecam** [comment]
ok!

**Comment by madewild** [comment]
cancelled
