### ISSUE TITLE
Change page number filter to 2 boxes

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#48]
To allow larger page numbers (e.g. 500) which might be inconvenient in a slider.

**Comment by madewild** [comment]
@flecam @bdeseure est-ce qu'on attend vraiment des nouveaux journeaux avec des numéros de pages très élevés (genre 500) ? Dans l'état actuel des choses cela me semble beaucoup de travail pour pas grand chose de modifier ce filtre...

**Comment by bdeseure** [comment]
Je ne suis pas sûr de comprendre de quoi il s'agit.

**Comment by madewild** [comment]
Le filtre "Numéro de page" est actuellement de type "slider" comme les années par exemple : 
![page_slider](https://user-images.githubusercontent.com/942488/197461508-a2305983-7184-4225-ad84-adc422b24040.png)

Antoine avait suggéré de le remplacer par un filtre de type "boxes", comme pour la date : 
![date_boxes](https://user-images.githubusercontent.com/942488/197461602-8a96c23b-4778-4f9e-91b9-5b99b8df1b4c.png)

On pourrait ainsi taper directement les numéros de pages souhaités dans les boîtes plutôt que de faire coulisser le curseur. Mais est-ce vraiment utile ?

**Comment by bdeseure** [comment]
Franchement je n'ai pas de préférence.

**Comment by madewild** [comment]
Je propose alors de laisser en l'état. Si ce besoin réapparaît plus tard (par exemple lors d'ajouts de titres avec beaucoup de pages), on pourra toujours réssuciter cette issue.
