### ISSUE TITLE
Add (un)select all option for checkbox filters

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#50]
An idea to be discussed later: we could add a "(Un)Select all" button, which could allow to go faster if the user only wants to (un)select one or two newspaper(s) (the same could be done for other filters with checkboxes). But this "(Un)Select all" button should work without activating the filter, otherwise it could be problematic.

_Originally posted by @anjacque in https://github.com/madewild/CAMille/issues/36#issuecomment-916213732_

**Comment by madewild** [comment]
@flecam @bdeseure première version ici, uniquement pour les journaux : https://dev.camille-ulb-kbr.be/?query=chicon&sortcrit=relevance&paper=JB421
Le bouton "Tout" permet de tout sélectionner d'un coup. On peut affiner en fonction de votre retour, et quand c'est bon on étend aux autres filtres de type checkbox (mois et jour de la semaine).

**Comment by madewild** [comment]
@flecam @bdeseure avez-vous testé ? quel est votre feedback ?

**Comment by bdeseure** [comment]
Je pense que ça fonctionne parfaitement.

**Comment by madewild** [comment]
OK alors j'étends aux autres filtres de ce type

**Comment by madewild** [comment]
Le bouton "Tout" a été étendu aux mois et aux jours de la semaine.
@flecam @bdeseure pouvez-vous tester sur https://dev.camille-ulb-kbr.be/?query=test ?

Attention, il faut peut-être rafraîchir le cache (CTRL+SHIFT+R dans Chrome) car le fichier Javascript a été modifié et il est possible que le navigateur conserve l'ancien en mémoire ce qui fait que les boutons "Tout" ne semblent pas fonctionner dans un premier temps...

**Comment by flecam** [comment]
Moi, ça marche, c'est cool!
