### ISSUE TITLE
Update about page + readme file in export

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#52]
Change names...

**Comment by madewild** [comment]
Replaced Antoine by Brecht on about page.
Need to leave Antoine? Other people to add (Alexia...)?

Not sure what we wanted to change in the README...

**Comment by flecam** [comment]
Il faut effectivement mettre Brecht à la place d'Antoine (y compris dans le comité scientifique). 
Pour ajouter Alexia, il faudrait ajouter une phrase sur l'équipe de recherche et donc ajouter Manon Libert et Sébastien (et toi!!! si tu as envie!!). Mais comme l'équipe de recherche est mouvante, ce n'est pas trop pénible de changer régulièrement?

**Comment by madewild** [comment]
First change done on https://dev.camille-ulb-kbr.be/?page=about
For me we can leave like that if OK for you...

**Comment by madewild** [comment]
@flecam on laisse comme ça ou pas ?

**Comment by flecam** [comment]
Je ne vois pas tes changements. En cliquant sur l'URL, je retombe encore sur la page avec Antoine.

**Comment by madewild** [comment]
J'avais changé dans "Comité scientifique de CAMille" mais j'avais oublié la seconde occurence dans "Le projet".
Cela devrait être OK à présent : https://dev.camille-ulb-kbr.be/?page=about

Autre chose à modifier ou je peux fermer cette issue ?
