### ISSUE TITLE
Add Petit Bleu newspaper

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#56]

**Comment by madewild** [comment]
Si je comprends bien, le Petit Bleu est divisé en deux cotes : JB685 et JB685A.
Le premier dossier JB685 contient 21498 fichiers XML à la racine plus deux répertoires : 
* pdf : 6202 fichiers PDF
* xml : 16110 fichiers XML
Le second dossier JB685A contient juste deux répertoires : 
* pdf : 192 fichiers PDF
* xml : 958 fichiers XML

J'avoue que je suis un peu perdu avec ces nombres qui ne correspondent pas du tout... @flecam @bdeseure est-ce qu'on peut prévoir une courte réunion pour discuter des options ?

**Comment by bdeseure** [comment]
Cher Max,

Le JB685A contient seulement les mois de mai à novembre de l'année 1897. Ces mêmes mois sont également présents dans le JB685 néanmois. Je demanderai plus d'info à KBR, mais à prémière vue je suggère d'ignorer la JB685A.

Brecht

**Comment by madewild** [comment]
D'accord, mais même dans JB685 il y a des grosses disparités entre les PDF et les XML. Cela risque de poser des problèmes d'affichages quand on clique sur un titre pour visualiser un PDF si celui-ci n'existe pas. :/

**Comment by bdeseure** [comment]
Il y a donc trop peu de pdf? Bizarre. Il faudra contrôler du côté de KBR.

Ce qui me frappe c'est que sur le disque dur je ne retrouve que les formats xml. Te souviens-tu comment on a fait pour les pdf?

**Comment by madewild** [comment]
Oui il y a moins de PDFs que de XMLs pour JB685. Pour les autres titres, j'avais le même nombre de chaque sur le disque dur qui m'avait été fourni par Antoine, je ne sais pas pourquoi tu ne vois pas les PDFs.

**Comment by bdeseure** [comment]
Est-ce que tu disposes du disque dur CAMille 2? Sur la CAMIlle 1, que j'ai moi, il n'y a pas les PDFs pour le petit bleu. Je me souviens qu'ils ont été livrés par KBR dans un deuxième temps. Je me renseignerai auprès KBR pour les PDFs manquants.

**Comment by madewild** [comment]
Oui j'ai le disque dur CAMille 2 avec une partie des PDFs. Tiens-moi au courant alors, je vais déjà importer les XML...

**Comment by madewild** [comment]
@bdeseure sur le disque CAMille 1, dans le répertoire JB685 je trouve 37608 fichiers XML, ce qui semble correspondre aux chiffres ci-dessus pour le disque CAMille 2 (21498 + 16110). Par contre si je regarde le détail, 10 premiers fichiers : 

```bash
KB_JB685_1894-05-01_01-0001.xml
KB_JB685_1894-05-01_01-0002.xml
KB_JB685_1894-05-01_01-0003.xml
KB_JB685_1894-05-01_01-0004.xml
KB_JB685_1894-05-01_01-mets.xml
KB_JB685_1894-05-02_01-0001.xml
KB_JB685_1894-05-02_01-0002.xml
KB_JB685_1894-05-02_01-0003.xml
KB_JB685_1894-05-02_01-0004.xml
KB_JB685_1894-05-02_01-mets.xml
```

Doit-on garder les fichiers -mets ?
Je suis en train de dézipper les PDF, ça prend un certain temps ;)

**Comment by madewild** [comment]
Après extraction, il n'y a que 37366 fichiers PDF. Il faut que j'analyse un peu plus pour voir ce qui manque...

**Comment by bdeseure** [comment]
@madewild Tu travailles bien dans le dossier PB_PDF? C'est celui qui est nouveau. Le dossier JB685 est identique a celui que tu avais déjà.

Les mets contiennent tout le texte du journal, tandis que les autres xml représentent des pages individuelles. Il ne faut donc pas garder les mets. 

Pour les pdfs égalament il faut seulement garder les pages individuelles.

**Comment by madewild** [comment]
Oui j'ai dézippé PB_PDF. Je vais ignorer les mets des deux côtés et voir si la petite différence de 250 fichiers subsiste ou pas...

**Comment by madewild** [comment]
OK, je confirme que les 242 PDF manquants sont tous des fichiers mets donc cela ne pose pas de problème

**Comment by madewild** [comment]
Il reste donc 31162 fichiers XML et PDF qui concernent des pages individuelles et non des éditions complètes

**Comment by madewild** [comment]
J'ai fini d'importer les XML et je suis occupé avec les PDFs, mais j'ai un petit problème avec ces fichiers:

Processing KB_JB685_1895-02-29_01-0001
Processing KB_JB685_1895-02-29_01-0002
Processing KB_JB685_1895-02-29_01-0003
Processing KB_JB685_1895-02-29_01-0004

Le 29 février 1895 ??? Cette date n'existe pas ! D'ailleurs l'édition du lendemain est datée du 2 mars... Je suis embêté car Elasticsearch refuse d'encoder cette date, mais je ne veux pas faire de la réécriture historique (il est bien écrit "vendredi 29 février 1895" sur la une du journal). Une idée de comment procéder ?

**Comment by bdeseure** [comment]
Problème intéressant :)

Je ferai quand-même la rééricture, puisque ce n'est qu'au niveau des métadonnées. La date d'origine restera visible dans le viewer.

**Comment by madewild** [comment]
OK on valide avec @flecam et je peux faire ça.

En attendand, les 31158 autres pages du Petit Bleu sont accessibles en dev : https://dev.camille-ulb-kbr.be/?query=*&paper=JB685

**Comment by bdeseure** [comment]
Super!
