### ISSUE TITLE
Integrate ULB CAS

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#58]
Check possibility outside ulb.be domain...
Alternative: ad-hoc accounts for students

**Comment by madewild** [comment]
Email sent on 29 September but still no reply from them...

**Comment by madewild** [comment]
The previous tech person left ULB, hence the silence.
Meeting planned this 8 November with his replacement.

**Comment by madewild** [comment]
Will be deployed in dev shortly. Postponing to next milestone for prod integration, since it raises many questions about whom can access what and at what level we need to define this (students, colleagues, departments vs research centre, etc.)

**Comment by madewild** [comment]
@flecam @bdeseure le CAS ULB est finalement activé en dev ! Pouvez-vous essayer de vous connecter sur https://dev.camille-ulb-kbr.be/ pour confirmer que ça fonctionne ?

**Comment by bdeseure** [comment]
J'ai accès. Qu'est-ce que le CAS?

**Comment by madewild** [comment]
https://dev.camille-ulb-kbr.be/ redirige automatique vers https://auth.ulb.be/login?service=https%3a%2f%2fdev.camille-ulb-kbr.be%2f ou on peut entrer ses credentials ULB. Si tu étais déjà connecté à l'intranet via une autre application (Mon ULB, portail du personnel, UV, etc.) il est possible que tes identifiants ne te soient pas redemandés.

**Comment by bdeseure** [comment]
OK j'ai accès avec mes credentials ULB

**Comment by madewild** [comment]
Implemented in dev, implications to discuss before merging to prod...
