### ISSUE TITLE
Change DNS to LaPIJ subdomain

### ISSUE THREAD

**Issue by madewild** [madewild/CAMille#59]
Check with @laurence001 who is maintaining https://lapij.ulb.ac.be/

**Comment by laurence001** [comment]
Bonjour Max, y a-t-il quelque chose que je dois faire de mon côté? Ou tout est ok? Merci !

**Comment by madewild** [comment]
Hello, l'idée serait de laisser tomber le nom de domaine https://www.camille-ulb-kbr.be/ et d'intégrer la plateforme à LaPIJ, par exemple sur https://camille.lapij.ulb.ac.be/ ou https://lapij.ulb.ac.be/camille (évitons de réutiliser https://lapij.ulb.ac.be/camille-centre-darchives-sur-les-medias-et-linformation-ulb-kbr/ car l'URL est un peu longue ;)
Il faut vérifier avec l'ULB si on peut faire une redirection DNS vers une adresse IP d'Amazon (car le site de CAMille resterait hosté sur AWS, au moins dans un premier temps).
Sidenote: pourquoi est-ce toujours https://lapij.ulb.ac.be/ et non https://lapij.ulb.be/ ? Cette dernière adresse renvoie une erreur de certificat et puis une erreur 404 de dev.ulb.ac.be

**Comment by laurence001** [comment]
Il que tu voies ça avec la cellule web car je n'ai aucun accès à tout cela (juste au serveur pour transférer des fichiers mais aucune maîtrise sur les DNS, nom de domaine etc.) Les contacts sont Marc.Albert (at l'université) ou alors Cellule.web (at l'université).

**Comment by madewild** [comment]
@flecam la première partie fonctionne : https://lapij.ulb.ac.be/camille redirige automatiquement vers https://www.camille-ulb-kbr.be/
Maintenant il faut voir si c'est suffisant ou si on veut que l'adresse lapij reste affichée dans le navigateur...

**Comment by flecam** [comment]
J'imagine que c'est beaucoup plus compliqué si on veut que le lapij reste affiché? Dans ce cas, ce n'est pas prioritaire. Là, c'est déjà bien.

**Comment by madewild** [comment]
Par forcément plus compliqué mais il y a un risque d'interférence avec le WordPress de LaPIJ... Je regarde ça.

**Comment by madewild** [comment]
Bon pas possible de faire mieux finalement puisque l'ULB ne permet pas l'usage du proxy...

**Comment by madewild** [comment]
Juste une chose : est-ce qu'on ajoute un onglet CAMille dans le menu sur https://lapij.ulb.be/ ?
Si oui, @laurence001 tu pourrais t'en charger dans WordPress ?
Attention il ne faut pas oublier que ce sera frustrant pour la plupart des utilisateurs puisqu'ils n'auront pas le login/mdp et seront donc bloqués à l'entrée...

**Comment by laurence001** [comment]
Bonjour Max,

Il faut poser la question à Florence, en copie. Je peux ajouter l'onglet 
mais s'il s'agit d'un accès protégé, je me demande si ce n'est pas mieux 
de l'ajouter directement dans le thème avec l'ouverture dans une 
nouvelle fenêtre. Dites-moi ce qu'il faut faire, merci !

Laurence

Le 2022-09-29 12:55, Max De Wilde a écrit :

> Juste une chose : est-ce qu'on ajoute un onglet CAMille dans le menu 
> sur https://lapij.ulb.be/ ?
> Si oui, @laurence001 [1] tu pourrais t'en charger dans WordPress ?
> Attention il ne faut pas oublier que ce sera frustrant pour la plupart 
> des utilisateurs puisqu'ils n'auront pas le login/mdp et seront donc 
> bloqués à l'entrée...
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/laurence001
[2] 
https://github.com/madewild/CAMille/issues/59#issuecomment-1262111866
[3]

**Comment by laurence001** [comment]
Bonjour,

Je pense que ce n’est pas utile. Je préfèrerais que sur la page CAMille du Lapij (https://lapij.ulb.ac.be/camille-centre-darchives-sur-les-medias-et-linformation-ulb-kbr/), nous puissions mettre un petit bloc menant vers la plateforme. Elena a déjà des idées.
Merci,
Florence


--
Professeure invitée – Université de Montréal (2022-23)
Chaire de journalisme - Université Libre de Bruxelles (ULB)
Revue Sur le journalisme, About Journalism, Sobre Jornalismo<http://www.surlejournalisme.com/rev>
ReSIC<http://resic.ulb.ac.be/>, LaPIJ<https://lapij.ulb.ac.be/> et Camille<https://lapij.ulb.ac.be/camille-centre-darchives-sur-les-medias-et-linformation-ulb-kbr/>
Arènes<https://arenes.eu/> (Université de Rennes 1)
@florlecam


De : Laurence Dierickx ***@***.***>
Date : jeudi 29 septembre 2022 à 11:58
À : madewild/CAMille ***@***.***>, LE CAM Florence ***@***.***>
Cc : madewild/CAMille ***@***.***>, Mention ***@***.***>
Objet : Re: [madewild/CAMille] Change DNS to LaPIJ subdomain (Issue #59)


Bonjour Max,

Il faut poser la question à Florence, en copie. Je peux ajouter l'onglet mais s'il s'agit d'un accès protégé, je me demande si ce n'est pas mieux de l'ajouter directement dans le thème avec l'ouverture dans une nouvelle fenêtre. Dites-moi ce qu'il faut faire, merci !

Laurence



Le 2022-09-29 12:55, Max De Wilde a écrit :



Juste une chose : est-ce qu'on ajoute un onglet CAMille dans le menu sur https://lapij.ulb.be/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flapij.ulb.be%2F&data=05%7C01%7CFlorence.Le.Cam%40ulb.be%7C99a2a6c0ac7e41093a6608daa2337503%7C30a5145e75bd4212bb028ff9c0ea4ae9%7C0%7C0%7C638000639127643693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xewKN9h6waNY4qhMpbTGXf1dCd%2FyAx4b5lbBFTgr4Nk%3D&reserved=0> ?
Si oui, @laurence001<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flaurence001&data=05%7C01%7CFlorence.Le.Cam%40ulb.be%7C99a2a6c0ac7e41093a6608daa2337503%7C30a5145e75bd4212bb028ff9c0ea4ae9%7C0%7C0%7C638000639127643693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sXp6Zi6OZa1HeQvVjirClvh%2FSYwRo%2FsipYNoxhjtT2s%3D&reserved=0> tu pourrais t'en charger dans WordPress ?
Attention il ne faut pas oublier que ce sera frustrant pour la plupart des utilisateurs puisqu'ils n'auront pas le login/mdp et seront donc bloqués à l'entrée...
